### ISSUE TITLE
centos7.4搭建失败

### ISSUE THREAD

**Issue by Zayia** [234150476/PUBG-Cloud-Radar#1]
最后提示如下
`for i in pcap-savefile.manfile.in; do \
	/usr/bin/install -c -m 644 `echo $i | sed 's/.manfile.in/.manfile/'` \
	    /usr/local/share/man/man5/`echo $i | sed 's/.manfile.in/.5/'`; done
for i in pcap-filter.manmisc.in pcap-linktype.manmisc.in pcap-tstamp.manmisc.in; do \
	/usr/bin/install -c -m 644 `echo $i | sed 's/.manmisc.in/.manmisc/'` \
	    /usr/local/share/man/man7/`echo $i | sed 's/.manmisc.in/.7/'`; done
-bash: cd: PUBG-Cloud-Radar/: No such file or directory
npm WARN saveError ENOENT: no such file or directory, open '/root/libpcap-1.8.1/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/libpcap-1.8.1/package.json'
npm WARN libpcap-1.8.1 No description
npm WARN libpcap-1.8.1 No repository field.
npm WARN libpcap-1.8.1 No README data
npm WARN libpcap-1.8.1 No license field.

up to date in 0.143s
/root/.nvm/v9.8.0/bin/pino -> /root/.nvm/v9.8.0/lib/node_modules/pino/bin.js
+ pino@4.16.1
added 28 packages in 5.023s
/root/.nvm/v9.8.0/bin/forever -> /root/.nvm/v9.8.0/lib/node_modules/forever/bin/forever
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/forever/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ forever@0.15.3
added 120 packages in 17.004s
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: index.js
error:   Cannot start forever
error:   script /root/libpcap-1.8.1/index.js does not exist.
搭建完成
`

**Comment by 234150476** [comment]
问题修复了在下载完libpcap-1.8.1后没有cd成功

**Comment by 234150476** [comment]
我添加了cd到root在cd到libpcap-1.8.1就可以安装了

**Comment by 234150476** [comment]
原始是再次clon但这样会浪费很多服务器流量

**Comment by Zayia** [comment]
嗯，后来自己CD /ROOT后自己执行了后续，已经搞定了，就是反馈一下这个问题
